CREATE TABLE logloop.events
(
  uuid uuid NOT NULL, -- Unique identifier of event. Ideally generated by logging application.
  "timestamp" timestamp with time zone NOT NULL DEFAULT now(), -- Times when evnet ocurred. Ideally set be logging application in @timestamp field.
  message text,
  fields hstore NOT NULL, -- Any additional fields from log event's JSON data. Contained fields differ per event.
  CONSTRAINT pk_uuid PRIMARY KEY (uuid)
);
COMMENT ON TABLE logloop.events
  IS 'Log events. Expected to remain empty as log are saved in daily child tables.';
COMMENT ON COLUMN logloop.events.uuid IS 'Unique identifier of event. Ideally generated by logging application.';
COMMENT ON COLUMN logloop.events."timestamp" IS 'Times when evnet ocurred. Ideally set be logging application in @timestamp field.';
COMMENT ON COLUMN logloop.events.fields IS 'Any additional fields from log event''s JSON data. Contained fields differ per event.';